



export const shopingData = [
    {
      id: 1,
      name: 'Romance Rose Bouquet',
      price: 89.99,
      image: '/images/rose-bouquet.jpg',
      rating: 4.8,
      category: 'Bouquets',
      inStock: true,
      description: "Elegant arrangement of fresh red roses with baby's breath",
      discount: 10,
    },
    {
      id: 2,
      name: 'Spring Tulip Collection',
      price: 64.99,
      image: '/images/tulip-collection.jpg',
      rating: 4.5,
      category: 'Seasonal',
      inStock: true,
      description: 'Colorful mix of spring tulips in pastel shades',
    },
    {
      id: 3,
      name: 'Orchid Paradise',
      price: 129.99,
      image: '/images/orchid.jpg',
      rating: 4.9,
      category: 'Premium',
      inStock: true,
      description: 'Exotic purple orchids in a ceramic pot',
    },
    {
      id: 4,
      name: 'Sunflower Delight',
      price: 54.99,
      image: '/images/sunflower.jpg',
      rating: 4.7,
      category: 'Bouquets',
      inStock: true,
      description: 'Cheerful arrangement of sunflowers',
    },
    {
      id: 5,
      name: 'Birthday Surprise',
      price: 99.99,
      image: '/images/birthday.jpg',
      rating: 4.6,
      category: 'Special',
      inStock: true,
      description: 'Mixed flowers with birthday decorations',
      discount: 15,
    },
    {
      id: 6,
      name: 'White Lily Bundle',
      price: 74.99,
      image: '/images/lily.jpg',
      rating: 4.8,
      category: 'Classic',
      inStock: true,
      description: 'Pure white lilies with green foliage',
    },
    {
      id: 7,
      name: 'Garden Mix',
      price: 69.99,
      image: '/images/garden-mix.jpg',
      rating: 4.4,
      category: 'Mixed',
      inStock: true,
      description: 'Colorful mix of garden flowers',
    },
    {
      id: 8,
      name: 'Peace Lily Plant',
      price: 45.99,
      image: '/images/peace-lily.jpg',
      rating: 4.7,
      category: 'Indoor',
      inStock: true,
      description: 'Air-purifying peace lily in decorative pot',
    },
    {
      id: 9,
      name: 'Premium Rose Box',
      price: 159.99,
      image: '/images/rose-box.jpg',
      rating: 5.0,
      category: 'Luxury',
      inStock: true,
      description: 'Long-lasting roses in elegant gift box',
      discount: 20,
    },
    {
      id: 10,
      name: 'Wildflower Bouquet',
      price: 49.99,
      image: '/images/wildflower.jpg',
      rating: 4.6,
      category: 'Natural',
      inStock: true,
      description: 'Fresh picked wildflowers arrangement',
    },
  ];
